matrix:
  include:
    - language: node_js
      script: npm run test:node
      node_js: "stable"
      env:
        - NAME="Node stable"
    - language: node_js
      script: npm run test:node
      node_js: "10"
      env:
        - NAME="Node 10"
    - language: node_js
      script: npm run test:node
      node_js: "8"
      env:
        - NAME="Node 8"
    - language: node_js
      script: npm run test:node
      node_js: "6"
      env:
        - NAME="Node 6"
    - language: node_js
      node_js: "8"
      sudo: required
      env:
        - NAME="Web"
      services:
        - xvfb
      addons:
        apt:
          sources:
            - google-chrome
          packages:
            - google-chrome-stable
      script: npm run test:web
