name: Tests

on: [push, pull_request]

jobs:
  specs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, latest]
    steps:
      - uses: actions/checkout@v3
      - name: Node.js specs ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run test:node
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Linting / Formatting
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run test:format
  web-specs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3
      - name: Node.js web specs ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
        env:
          MOZ_HEADLESS: 1
          CI: travis
      - name: Setup Firefox
        uses: browser-actions/setup-firefox@latest
        with:
          firefox-version: latest
      - name: Setup Chrome
        uses: browser-actions/setup-chrome@latest
      - run: google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
      - run: npm ci
      - run: npm run test:web
